##########################################################################################################################
# File automatically-generated by tool: [projectgenerator] version: [4.8.0-B50] date: [Thu Apr 23 17:52:34 ICT 2026] 
##########################################################################################################################

# ------------------------------------------------
# Generic Makefile (based on gcc)
#
# ChangeLog :
#	2017-02-10 - Several enhancements + project update mode
#   2015-07-22 - first version
# ------------------------------------------------

######################################
# target
######################################
TARGET = TrackingFirmWare


######################################
# building variables
######################################
# debug build?
DEBUG = 1
# optimization
OPT = -Og


#######################################
# paths
#######################################
# Build path
BUILD_DIR = build

######################################
# source
######################################
# C sources
C_SOURCES =  \
Core/Src/main.c \
Core/Src/gpio.c \
Core/Src/dcache.c \
Core/Src/i2c.c \
Core/Src/spi.c \
Core/Src/usart.c \
Core/Src/usb.c \
Core/Src/stm32h5xx_it.c \
Core/Src/stm32h5xx_hal_msp.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_cortex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dcache.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rcc_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_flash_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_gpio.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_dma_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pwr_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_exti.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_i2c.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_i2c_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_spi.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_spi_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_uart.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_uart_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pcd.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_pcd_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_ll_usb.c \
Core/Src/system_stm32h5xx.c \
Core/Src/sysmem.c \
Core/Src/syscalls.c \
Core/Src/icache.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_icache.c \
Core/Src/lptim.c \
Core/Src/rtc.c \
Core/Src/tim.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_lptim.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rtc.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_rtc_ex.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_tim.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_tim_ex.c \
Core/Src/adc.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_adc.c \
Drivers/STM32H5xx_HAL_Driver/Src/stm32h5xx_hal_adc_ex.c

#SYNAPTIX
SYNAPTIX_DIR := SynaptiX_FDK
USB_TINY_DIR := SynaptiX_FDK/lib/tinyusb

include $(SYNAPTIX_DIR)/synaptix.mk
include $(USB_TINY_DIR)/src/tinyusb.mk

C_SOURCES += $(addprefix $(USB_TINY_DIR)/,$(TINYUSB_SRC_C))# Add define for USB tiny
# SYNAPTIX SOURCES
C_SOURCES += $(SYNAPTIX_SOURCES)

# ASM sources
ASM_SOURCES =  \
startup_stm32h563xx.s

# ASMM sources
ASMM_SOURCES = 



#######################################
# binaries
#######################################
PREFIX = arm-none-eabi-
# The gcc compiler bin path can be either defined in make command via GCC_PATH variable (> make GCC_PATH=xxx)
# either it can be added to the PATH environment variable.
ifdef GCC_PATH
CC = $(GCC_PATH)/$(PREFIX)gcc
AS = $(GCC_PATH)/$(PREFIX)gcc -x assembler-with-cpp
CP = $(GCC_PATH)/$(PREFIX)objcopy
SZ = $(GCC_PATH)/$(PREFIX)size
else
CC = $(PREFIX)gcc
AS = $(PREFIX)gcc -x assembler-with-cpp
CP = $(PREFIX)objcopy
SZ = $(PREFIX)size
endif
HEX = $(CP) -O ihex
BIN = $(CP) -O binary -S
 
#######################################
# CFLAGS
#######################################
# cpu
CPU = -mcpu=cortex-m33

# fpu
FPU = -mfpu=fpv5-sp-d16

# float-abi
FLOAT-ABI = -mfloat-abi=hard

# mcu
MCU = $(CPU) -mthumb $(FPU) $(FLOAT-ABI)

# macros for gcc
# AS defines
AS_DEFS = 

# C defines
C_DEFS =  \
-DUSE_HAL_DRIVER \
-DSTM32H563xx \
-DCFG_TUSB_MCU=OPT_MCU_STM32H5

# AS includes
AS_INCLUDES = 

# C includes
C_INCLUDES =  \
-ICore/Inc \
-IDrivers/STM32H5xx_HAL_Driver/Inc \
-IDrivers/STM32H5xx_HAL_Driver/Inc/Legacy \
-IDrivers/CMSIS/Device/ST/STM32H5xx/Include \
-IDrivers/CMSIS/Include

#SynaptiX Inc
C_INCLUDES += -I$(SYNAPTIX_DIR)/app \
			  -I$(SYNAPTIX_DIR)/app/user/sx_cdc \
			  -I$(SYNAPTIX_DIR)/app/user/sx_msc \
			  -I$(SYNAPTIX_DIR)/app/user/sx_mqtt \
			  -I$(SYNAPTIX_DIR)/app/user/sx_ex_storage \
			  -I$(SYNAPTIX_DIR)/app/user/at_usb \
			  -I$(SYNAPTIX_DIR)/board \
			  -I$(SYNAPTIX_DIR)/services/logger \
			  -I$(SYNAPTIX_DIR)/services/littlefs \
			  -I$(SYNAPTIX_DIR)/services/cJSON \
			  -I$(SYNAPTIX_DIR)/services/OS \
			  -I$(SYNAPTIX_DIR)/services/filesystem \
			  -I${SYNAPTIX_DIR}/services/shell \
			  -I$(SYNAPTIX_DIR)/services/fatfs \
			  -I$(SYNAPTIX_DIR)/services/sx_fatfs \
			  -I$(SYNAPTIX_DIR)/services/mqtt \
			  -I$(SYNAPTIX_DIR)/services/sleepmanager \
			  -I${SYNAPTIX_DIR}/services/read_bat \
			  -I$(SYNAPTIX_DIR)/utils/cqueue \
			  -I$(SYNAPTIX_DIR)/utils/mem \
			  -I$(SYNAPTIX_DIR)/utils/delay \
			  -I$(SYNAPTIX_DIR)/utils/def \
			  -I$(SYNAPTIX_DIR)/utils/delay \
			  -I$(SYNAPTIX_DIR)/utils/filter \
			  -I$(SYNAPTIX_DIR)/components/can \
			  -I$(SYNAPTIX_DIR)/components/flash \
			  -I$(SYNAPTIX_DIR)/components/gpio \
			  -I$(SYNAPTIX_DIR)/components/i2c \
			  -I$(SYNAPTIX_DIR)/components/spi \
			  -I$(SYNAPTIX_DIR)/components/uart \
			  -I$(SYNAPTIX_DIR)/components/timer \
			  -I$(SYNAPTIX_DIR)/components/gps \
			  -I$(SYNAPTIX_DIR)/components/modem \
			  -I$(SYNAPTIX_DIR)/components/sim76xx \
			  -I$(SYNAPTIX_DIR)/components/usb_cdc_tiny \
			  -I$(SYNAPTIX_DIR)/components/usb_msc_tiny \
			  -I$(SYNAPTIX_DIR)/components/external_flash \
		      -I$(SYNAPTIX_DIR)/components/sleep \
			  -I$(SYNAPTIX_DIR)/components/imu \
			  -I$(SYNAPTIX_DIR)/components/rtc \
#USB tiny
C_INCLUDES += -I$(USB_TINY_DIR)/src \
			  -I$(USB_TINY_DIR)/src/common \
			  -I$(USB_TINY_DIR)/src/device \
			  -I$(USB_TINY_DIR)/hw \
			  -I$(USB_TINY_DIR)/hw/bsp \

# compile gcc flags
ASFLAGS = $(MCU) $(AS_DEFS) $(AS_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

CFLAGS += $(MCU) $(C_DEFS) $(C_INCLUDES) $(OPT) -Wall -fdata-sections -ffunction-sections

ifeq ($(DEBUG), 1)
CFLAGS += -g -gdwarf-2
endif


# Generate dependency information
CFLAGS += -MMD -MP -MF"$(@:%.o=%.d)"


#######################################
# LDFLAGS
#######################################
# link script
LDSCRIPT = STM32H563xx_FLASH.ld

# libraries
LIBS = -lc -lm -lnosys 
LIBDIR = 
LDFLAGS = $(MCU) -specs=nano.specs -T$(LDSCRIPT) $(LIBDIR) $(LIBS) -Wl,-Map=$(BUILD_DIR)/$(TARGET).map,--cref -Wl,--gc-sections
LDFLAGS += -u _printf_float

# default action: build all
all: $(BUILD_DIR)/$(TARGET).elf $(BUILD_DIR)/$(TARGET).hex $(BUILD_DIR)/$(TARGET).bin


#######################################
# build the application
#######################################
# list of objects
OBJECTS = $(addprefix $(BUILD_DIR)/,$(notdir $(C_SOURCES:.c=.o)))
vpath %.c $(sort $(dir $(C_SOURCES)))
# list of ASM program objects
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASM_SOURCES:.s=.o)))
vpath %.s $(sort $(dir $(ASM_SOURCES)))
OBJECTS += $(addprefix $(BUILD_DIR)/,$(notdir $(ASMM_SOURCES:.S=.o)))
vpath %.S $(sort $(dir $(ASMM_SOURCES)))

$(BUILD_DIR)/%.o: %.c Makefile | $(BUILD_DIR) 
	$(CC) -c $(CFLAGS) -Wa,-a,-ad,-alms=$(BUILD_DIR)/$(notdir $(<:.c=.lst)) $< -o $@

$(BUILD_DIR)/%.o: %.s Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@
$(BUILD_DIR)/%.o: %.S Makefile | $(BUILD_DIR)
	$(AS) -c $(CFLAGS) $< -o $@

$(BUILD_DIR)/$(TARGET).elf: $(OBJECTS) Makefile
	$(CC) $(OBJECTS) $(LDFLAGS) -o $@
	$(SZ) $@

$(BUILD_DIR)/%.hex: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(HEX) $< $@
	
$(BUILD_DIR)/%.bin: $(BUILD_DIR)/%.elf | $(BUILD_DIR)
	$(BIN) $< $@	
	
$(BUILD_DIR):
	mkdir $@		

#######################################
# clean up
#######################################
clean:
	-powershell -NoProfile -Command "if (Test-Path '$(BUILD_DIR)') { Remove-Item -Recurse -Force '$(BUILD_DIR)' }"

flash:
	@echo Flashing $(TARGET)...
	STM32_Programmer_CLI -c port=SWD -w $(BUILD_DIR)/$(TARGET).hex -v --start
  
#######################################
# dependencies
#######################################
-include $(wildcard $(BUILD_DIR)/*.d)

# *** EOF ***
